### ISSUE TITLE
`--output yaml` not supported with `--list` option

### ISSUE THREAD

**Issue by yabberyabber** [jenkinsci/plugin-installation-manager-tool#284]
Steps to reproduce:
```
 % java -jar jenkins-plugin-manager-2.5.0.jar --plugins blueocean:1.24.3 --latest-specified --no-download -l --output yaml

Installed plugins:

Bundled plugins:

All requested plugins:
ace-editor 1.0.1
apache-httpcomponents-client-4-api 4.5.10-2.0
authentication-tokens 1.3
blueocean 1.24.3
blueocean-autofavorite 1.2.3
blueocean-bitbucket-pipeline 1.24.3
<etc etc etc>
```

This is the same output format as if I were to specify no `--output` arg at all. I would expect to see something like...
```
installedPlugins: []
bundledPlugins: []
requestedPlugins:
 - name: ace-editor
   version: 1.0.1
<etc etc etc>
```

My end-goal is to compute a complete dependency closure for a given set of plugins so that I can build a jenkins image in a reproducible way. I can scrape that info from the text-format output but it's a pain. Am I invoking the command wrong? Is there another tool I can use to compute the dependency closure which would be more recommended?
