### ISSUE TITLE
Write checksum to output list

### ISSUE THREAD

**Issue by mortenmj** [jenkinsci/plugin-installation-manager-tool#606]
### What feature do you want to see added?

We use this tool to create a lockfile for our plugins. This is used in a workflow where we download the distributed Jenkins container image, add the plugins we want, and republish to our own internal image registry.
To improve performance in this workflow, it would be very useful for us if this tool could also output the SHA256 checksums for the plugins. Less crucial, but also useful, would be to output the download URL(s) for the plugin.

YAML output that looks something like the following would, for example, work well in our use case:

```
- artifactId: "my-plugin"
  source:
    checksum: "<snip>"
    url: "<snip>"
    version: "1.0.0"
```
